// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Entity is the predicate function for entity builders.
type Entity func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
