// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/messaging.proto

package messagingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header_Entity_EntityType int32

const (
	Header_Entity_GROUP Header_Entity_EntityType = 0
	Header_Entity_USER  Header_Entity_EntityType = 1
)

// Enum value maps for Header_Entity_EntityType.
var (
	Header_Entity_EntityType_name = map[int32]string{
		0: "GROUP",
		1: "USER",
	}
	Header_Entity_EntityType_value = map[string]int32{
		"GROUP": 0,
		"USER":  1,
	}
)

func (x Header_Entity_EntityType) Enum() *Header_Entity_EntityType {
	p := new(Header_Entity_EntityType)
	*p = x
	return p
}

func (x Header_Entity_EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Header_Entity_EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messaging_proto_enumTypes[0].Descriptor()
}

func (Header_Entity_EntityType) Type() protoreflect.EnumType {
	return &file_proto_messaging_proto_enumTypes[0]
}

func (x Header_Entity_EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Header_Entity_EntityType.Descriptor instead.
func (Header_Entity_EntityType) EnumDescriptor() ([]byte, []int) {
	return file_proto_messaging_proto_rawDescGZIP(), []int{0, 0, 0}
}

type AckMessage_Status int32

const (
	AckMessage_Delivered AckMessage_Status = 0
	AckMessage_Read      AckMessage_Status = 1
)

// Enum value maps for AckMessage_Status.
var (
	AckMessage_Status_name = map[int32]string{
		0: "Delivered",
		1: "Read",
	}
	AckMessage_Status_value = map[string]int32{
		"Delivered": 0,
		"Read":      1,
	}
)

func (x AckMessage_Status) Enum() *AckMessage_Status {
	p := new(AckMessage_Status)
	*p = x
	return p
}

func (x AckMessage_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckMessage_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messaging_proto_enumTypes[1].Descriptor()
}

func (AckMessage_Status) Type() protoreflect.EnumType {
	return &file_proto_messaging_proto_enumTypes[1]
}

func (x AckMessage_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckMessage_Status.Descriptor instead.
func (AckMessage_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_messaging_proto_rawDescGZIP(), []int{2, 0}
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender    *Header_Entity         `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient *Header_Entity         `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	DateSent  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_sent,json=dateSent,proto3" json:"date_sent,omitempty"`
	MessageId string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_messaging_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetSender() *Header_Entity {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Header) GetRecipient() *Header_Entity {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *Header) GetDateSent() *timestamppb.Timestamp {
	if x != nil {
		return x.DateSent
	}
	return nil
}

func (x *Header) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Message string  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_messaging_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AckMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status AckMessage_Status `protobuf:"varint,2,opt,name=status,proto3,enum=AckMessage_Status" json:"status,omitempty"`
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_messaging_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_proto_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *AckMessage) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AckMessage) GetStatus() AckMessage_Status {
	if x != nil {
		return x.Status
	}
	return AckMessage_Delivered
}

type Header_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type Header_Entity_EntityType `protobuf:"varint,2,opt,name=type,proto3,enum=Header_Entity_EntityType" json:"type,omitempty"`
}

func (x *Header_Entity) Reset() {
	*x = Header_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_messaging_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header_Entity) ProtoMessage() {}

func (x *Header_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header_Entity.ProtoReflect.Descriptor instead.
func (*Header_Entity) Descriptor() ([]byte, []int) {
	return file_proto_messaging_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Header_Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Header_Entity) GetType() Header_Entity_EntityType {
	if x != nil {
		return x.Type
	}
	return Header_Entity_GROUP
}

var File_proto_messaging_proto protoreflect.FileDescriptor

var file_proto_messaging_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x02, 0x0a, 0x06, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x09, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x09,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x1a, 0x6a, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x21, 0x0a, 0x0a, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x4f, 0x55,
	0x50, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x22, 0x44, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x7c, 0x0a, 0x0a, 0x41, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x41, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x21,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x65, 0x64, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x10,
	0x01, 0x32, 0x36, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0b, 0x2e, 0x41,
	0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_messaging_proto_rawDescOnce sync.Once
	file_proto_messaging_proto_rawDescData = file_proto_messaging_proto_rawDesc
)

func file_proto_messaging_proto_rawDescGZIP() []byte {
	file_proto_messaging_proto_rawDescOnce.Do(func() {
		file_proto_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_messaging_proto_rawDescData)
	})
	return file_proto_messaging_proto_rawDescData
}

var file_proto_messaging_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_messaging_proto_goTypes = []interface{}{
	(Header_Entity_EntityType)(0), // 0: Header.Entity.EntityType
	(AckMessage_Status)(0),        // 1: AckMessage.Status
	(*Header)(nil),                // 2: Header
	(*Message)(nil),               // 3: Message
	(*AckMessage)(nil),            // 4: AckMessage
	(*Header_Entity)(nil),         // 5: Header.Entity
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_messaging_proto_depIdxs = []int32{
	5, // 0: Header.sender:type_name -> Header.Entity
	5, // 1: Header.recipient:type_name -> Header.Entity
	6, // 2: Header.date_sent:type_name -> google.protobuf.Timestamp
	2, // 3: Message.header:type_name -> Header
	2, // 4: AckMessage.header:type_name -> Header
	1, // 5: AckMessage.status:type_name -> AckMessage.Status
	0, // 6: Header.Entity.type:type_name -> Header.Entity.EntityType
	3, // 7: MessageService.SendMessage:input_type -> Message
	4, // 8: MessageService.SendMessage:output_type -> AckMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_messaging_proto_init() }
func file_proto_messaging_proto_init() {
	if File_proto_messaging_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_messaging_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_messaging_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_messaging_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_messaging_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_messaging_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messaging_proto_goTypes,
		DependencyIndexes: file_proto_messaging_proto_depIdxs,
		EnumInfos:         file_proto_messaging_proto_enumTypes,
		MessageInfos:      file_proto_messaging_proto_msgTypes,
	}.Build()
	File_proto_messaging_proto = out.File
	file_proto_messaging_proto_rawDesc = nil
	file_proto_messaging_proto_goTypes = nil
	file_proto_messaging_proto_depIdxs = nil
}
