// Code generated by entc, DO NOT EDIT.

package ent

import (
	"SafeSend/pkg/ent/entity"
	"SafeSend/pkg/ent/group"
	"SafeSend/pkg/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Group is the model entity for the Group schema.
type Group struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GroupName holds the value of the "groupName" field.
	GroupName string `json:"groupName,omitempty"`
	// MaxParticipants holds the value of the "maxParticipants" field.
	MaxParticipants int32 `json:"maxParticipants,omitempty"`
	// InviteOnly holds the value of the "inviteOnly" field.
	InviteOnly bool `json:"inviteOnly,omitempty"`
	// DateCreated holds the value of the "dateCreated" field.
	DateCreated time.Time `json:"dateCreated,omitempty"`
	// DateModified holds the value of the "dateModified" field.
	DateModified time.Time `json:"dateModified,omitempty"`
	// DateDeleted holds the value of the "dateDeleted" field.
	DateDeleted time.Time `json:"dateDeleted,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupQuery when eager-loading is set.
	Edges         GroupEdges `json:"edges"`
	entity_groups *uuid.UUID
	group_users   *uuid.UUID
}

// GroupEdges holds the relations/edges for other nodes in the graph.
type GroupEdges struct {
	// Users holds the value of the users edge.
	Users *User `json:"users,omitempty"`
	// Entities holds the value of the entities edge.
	Entities *Entity `json:"entities,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupEdges) UsersOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Users == nil {
			// The edge users was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// EntitiesOrErr returns the Entities value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupEdges) EntitiesOrErr() (*Entity, error) {
	if e.loadedTypes[1] {
		if e.Entities == nil {
			// The edge entities was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: entity.Label}
		}
		return e.Entities, nil
	}
	return nil, &NotLoadedError{edge: "entities"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Group) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case group.FieldInviteOnly:
			values[i] = new(sql.NullBool)
		case group.FieldMaxParticipants:
			values[i] = new(sql.NullInt64)
		case group.FieldGroupName:
			values[i] = new(sql.NullString)
		case group.FieldDateCreated, group.FieldDateModified, group.FieldDateDeleted:
			values[i] = new(sql.NullTime)
		case group.FieldID:
			values[i] = new(uuid.UUID)
		case group.ForeignKeys[0]: // entity_groups
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case group.ForeignKeys[1]: // group_users
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type Group", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Group fields.
func (gr *Group) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case group.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				gr.ID = *value
			}
		case group.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field groupName", values[i])
			} else if value.Valid {
				gr.GroupName = value.String
			}
		case group.FieldMaxParticipants:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field maxParticipants", values[i])
			} else if value.Valid {
				gr.MaxParticipants = int32(value.Int64)
			}
		case group.FieldInviteOnly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field inviteOnly", values[i])
			} else if value.Valid {
				gr.InviteOnly = value.Bool
			}
		case group.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dateCreated", values[i])
			} else if value.Valid {
				gr.DateCreated = value.Time
			}
		case group.FieldDateModified:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dateModified", values[i])
			} else if value.Valid {
				gr.DateModified = value.Time
			}
		case group.FieldDateDeleted:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dateDeleted", values[i])
			} else if value.Valid {
				gr.DateDeleted = value.Time
			}
		case group.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field entity_groups", values[i])
			} else if value.Valid {
				gr.entity_groups = new(uuid.UUID)
				*gr.entity_groups = *value.S.(*uuid.UUID)
			}
		case group.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field group_users", values[i])
			} else if value.Valid {
				gr.group_users = new(uuid.UUID)
				*gr.group_users = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// QueryUsers queries the "users" edge of the Group entity.
func (gr *Group) QueryUsers() *UserQuery {
	return (&GroupClient{config: gr.config}).QueryUsers(gr)
}

// QueryEntities queries the "entities" edge of the Group entity.
func (gr *Group) QueryEntities() *EntityQuery {
	return (&GroupClient{config: gr.config}).QueryEntities(gr)
}

// Update returns a builder for updating this Group.
// Note that you need to call Group.Unwrap() before calling this method if this Group
// was returned from a transaction, and the transaction was committed or rolled back.
func (gr *Group) Update() *GroupUpdateOne {
	return (&GroupClient{config: gr.config}).UpdateOne(gr)
}

// Unwrap unwraps the Group entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gr *Group) Unwrap() *Group {
	tx, ok := gr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Group is not a transactional entity")
	}
	gr.config.driver = tx.drv
	return gr
}

// String implements the fmt.Stringer.
func (gr *Group) String() string {
	var builder strings.Builder
	builder.WriteString("Group(")
	builder.WriteString(fmt.Sprintf("id=%v", gr.ID))
	builder.WriteString(", groupName=")
	builder.WriteString(gr.GroupName)
	builder.WriteString(", maxParticipants=")
	builder.WriteString(fmt.Sprintf("%v", gr.MaxParticipants))
	builder.WriteString(", inviteOnly=")
	builder.WriteString(fmt.Sprintf("%v", gr.InviteOnly))
	builder.WriteString(", dateCreated=")
	builder.WriteString(gr.DateCreated.Format(time.ANSIC))
	builder.WriteString(", dateModified=")
	builder.WriteString(gr.DateModified.Format(time.ANSIC))
	builder.WriteString(", dateDeleted=")
	builder.WriteString(gr.DateDeleted.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Groups is a parsable slice of Group.
type Groups []*Group

func (gr Groups) config(cfg config) {
	for _i := range gr {
		gr[_i].config = cfg
	}
}
